import type { EmailTemplate } from '../types/notificaciones.types';
import { NOTIFICATIONS_TENANT_ID } from '../constants/notificaciones.constants';

export const defaultEmailTemplates: EmailTemplate[] = [
  {
    id: 'tpl-order-confirmation',
    tenantId: NOTIFICATIONS_TENANT_ID,
    name: 'Confirmacion de pedido',
    purpose: 'confirmacion-pedido',
    subject: 'Pedido B2B-1042 confirmado',
    preheader: 'Hemos recibido tu pedido y ya esta en proceso.',
    html: '<h1>Pedido confirmado</h1><p>Hola Mariana Torres, tu pedido B2B-1042 fue confirmado.</p>',
    brandColor: '#2563eb',
    accentColor: '#10b981',
    logoUrl: 'https://dummyimage.com/120x40/2563eb/ffffff&text=ERP',
    active: true,
    updatedAt: '2026-05-14T01:00:00.000Z',
  },
  {
    id: 'tpl-dispatch',
    tenantId: NOTIFICATIONS_TENANT_ID,
    name: 'Despacho',
    purpose: 'despacho',
    subject: 'Tu pedido esta en ruta',
    preheader: 'La entrega salio del almacen.',
    html: '<h1>Despacho iniciado</h1><p>ETA estimada: hoy 15:30.</p>',
    brandColor: '#0f766e',
    accentColor: '#f59e0b',
    logoUrl: 'https://dummyimage.com/120x40/0f766e/ffffff&text=ERP',
    active: true,
    updatedAt: '2026-05-14T01:05:00.000Z',
  },
  {
    id: 'tpl-delivery',
    tenantId: NOTIFICATIONS_TENANT_ID,
    name: 'Entrega',
    purpose: 'entrega',
    subject: 'Entrega completada',
    preheader: 'Gracias por confirmar la recepcion.',
    html: '<h1>Entrega completada</h1><p>El documento de entrega ya esta disponible.</p>',
    brandColor: '#7c3aed',
    accentColor: '#06b6d4',
    logoUrl: 'https://dummyimage.com/120x40/7c3aed/ffffff&text=ERP',
    active: true,
    updatedAt: '2026-05-14T01:10:00.000Z',
  },
  {
    id: 'tpl-payment-reminder',
    tenantId: NOTIFICATIONS_TENANT_ID,
    name: 'Recordatorio de pago',
    purpose: 'recordatorio-pago',
    subject: 'Factura F-908 pendiente',
    preheader: 'Tienes un pago proximo a vencer.',
    html: '<h1>Recordatorio de pago</h1><p>Importe pendiente: S/ 4,820.00.</p>',
    brandColor: '#b45309',
    accentColor: '#2563eb',
    logoUrl: 'https://dummyimage.com/120x40/b45309/ffffff&text=ERP',
    active: true,
    updatedAt: '2026-05-14T01:15:00.000Z',
  },
  {
    id: 'tpl-account-recovery',
    tenantId: NOTIFICATIONS_TENANT_ID,
    name: 'Recuperacion de cuenta',
    purpose: 'recuperacion-cuenta',
    subject: 'Recupera tu acceso',
    preheader: 'Solicitud de recuperacion recibida.',
    html: '<h1>Recuperacion de cuenta</h1><p>Usa el codigo 482913 para continuar.</p>',
    brandColor: '#334155',
    accentColor: '#14b8a6',
    logoUrl: 'https://dummyimage.com/120x40/334155/ffffff&text=ERP',
    active: true,
    updatedAt: '2026-05-14T01:20:00.000Z',
  },
];
