// Rutas centralizadas START ERP
export const PATHS = {
  HOME: "/",
  AUTH: { LOGIN: "/auth/login", REGISTER: "/auth/register", FORGOT_PASSWORD: "/auth/forgot-password" },
  DASHBOARD: "/",
  CRM: "/crm",
  VENTAS: "/ventas",
  INVENTARIO: "/inventario",
  LOGISTICA: "/logistica",
  COMPRAS: "/compras",
  CALIDAD: "/calidad",
  FINANZAS: "/finanzas",
  DOCUMENTOS: "/documentos",
  REPORTES: "/reportes",
  NOTIFICACIONES: "/notificaciones",
  CONFIGURACION: "/configuracion",
  INTEGRACIONES: "/integraciones",
  PORTAL: {
    ROOT:          "/portal",
    LOGIN:         "/portal/login",
    FORGOT:        "/portal/forgot-password",
    MFA:           "/portal/mfa",
    DASHBOARD:     "/portal/dashboard",
    CATALOGO:      "/portal/catalogo",
    PEDIDOS:       "/portal/pedidos",
    FACTURAS:      "/portal/facturas",
    RECLAMOS:      "/portal/reclamos",
    EVALUACIONES:  "/portal/evaluaciones",
    PERFIL:        "/portal/perfil",
  },
} as const;
