export const ORDER_STATUS = {
  PENDING: 'PENDIENTE',
  PROCESSING: 'PROCESANDO',
  SHIPPED: 'EN CAMINO',
  DELIVERED: 'ENTREGADO',
  CANCELLED: 'CANCELADO',
} as const;

export const PRODUCT_STATUS = {
  ACTIVE: 'ACTIVO',
  INACTIVE: 'INACTIVO',
  OUT_OF_STOCK: 'SIN STOCK',
} as const;

export const LOGISTICS_STATUS = {
  PENDING: 'PENDIENTE',
  IN_TRANSIT: 'EN RUTA',
  COMPLETED: 'COMPLETADO',
} as const;
